version: "3.7"
services:
  app:
    build:
      args:
        user: rune
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: projects
    container_name: projects-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - projects

  db:
    image: mysql:5.7
    container_name: projects-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - projects

  nginx:
    image: nginx:alpine
    container_name: projects-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - projects

networks:
  projects:
    driver: bridge